[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["github_issue_summary_to_email"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/ManualTrigger","Category/Integration"]
  name = "github_issue_summary_to_email"
  org = "anjanasupun"
  version = "3.1.0"

